## Evaluation

In [32]:
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import mean_squared_error
import numpy as np
import seaborn as sns

Calculate average of a measurement, will be used in the next function

In [33]:
def average(data, measurement):
    avg = data[measurement].mean()
    return avg

Calculate error margin with mean square error. The percentage is calculated to get a comparable value. The error is divided by average of the measurement to get the percentage error. The mean square error, root mean square error and the percentage are added to a dataframe. You can chose to have a limitation of the error percetage by adding a redflag percent, the function will then return a dataframe with the error margin and a dataframe with only the measurement that did not meet the requierment. If a redflag percentage is not added then only the error margin dataframe will be returned.

In [34]:
def calc_error_margin(prediction, test, redflag_percent=False):
    test = test.iloc[:len(prediction),:]
    error_margin= pd.DataFrame()
    red_flags= pd.DataFrame()
    ansur=pd.read_csv('../data/processed/ANSURIImalefemale.csv')
    for m in list(prediction.columns[:]):
        mse= mean_squared_error(prediction[m], test[m])
        rmse=np.sqrt(mse)
        avg = average(ansur,m)
        error_margin[m]= {'mse': mse, 'rmse': rmse, '%' : (rmse/avg)*100 }
        if redflag_percent!= False and (rmse/avg)*100>redflag_percent:
            red_flags[m]=error_margin[m]
    if redflag_percent!=False:
        return error_margin, red_flags
    return error_margin

The function below plots the actual value in realation to the predicted value. It is a scatter plot where hue is based on gender. The gender 0 represents females while 1 represent males.

In [35]:
def plot_errors(error_measurments, prediction, test):
   y_test=test.iloc[:,1:94].drop('weightkg',axis=1).drop('stature',axis=1)
   for r in error_measurments:
      sns.scatterplot(x = prediction[r], y = y_test[r], hue=test["Gender"])
      plt.plot([min(prediction[r]), max(prediction[r])], [min(prediction[r]), max(prediction[r])],linewidth=3, c="red")
      plt.title(r)
      plt.xlabel("Predicted")
      plt.ylabel("Actual")
      plt.show()

Here we are testing the errors of different models.

In [46]:

test=pd.read_csv('../data/processed/ANSURIItest.csv')
p=pd.read_csv('../output/anthro_results/predict_test_bambi_c.csv')

In [47]:
error=calc_error_margin(p, test)
error

,abdominalextensiondepthsitting,acromialheight,acromionradialelength,anklecircumference,axillaheight,balloffootcircumference,balloffootlength,biacromialbreadth,bicepscircumferenceflexed,bicristalbreadth,...,trochanterionheight,verticaltrunkcircumferenceusa,waistbacklength,waistbreadth,waistcircumference,waistdepth,waistfrontlengthsitting,waistheightomphalion,wristcircumference,wristheight
mse,278.841073,206.472482,119.057354,145.538948,224.178610,94.646165,71.167173,210.661912,307.361227,196.397998,...,778.984918,1773.530735,395.652344,246.553049,1857.389674,225.884951,558.879046,397.523739,37.377932,489.314311
rmse,16.698535,14.369150,10.911341,12.063952,14.972595,9.728626,8.436064,14.514197,17.531721,14.014207,...,27.910301,42.113308,19.891012,15.702008,43.097444,15.029469,23.640623,19.937997,6.113749,22.120450
%,6.775114,1.021871,3.332985,5.364346,1.152085,3.983996,4.331637,3.635783,5.142259,5.100991,...,3.161781,2.583148,4.319206,4.941623,4.712671,6.543826,6.270659,1.932911,3.617540,2.664922

In [43]:
error=calc_error_margin(p5, test)
error

,abdominalextensiondepthsitting,acromialheight,acromionradialelength,anklecircumference,axillaheight
mse,181.749227,253.525188,152.616819,126.686040,147.344185
rmse,13.481440,15.922474,12.353818,11.255489,12.138541
%,5.469839,1.132336,3.773605,5.004855,0.934015

In [40]:
error=calc_error_margin(p4, test)
error

      abdominalextensiondepthsitting  acromialheight  acromionradialelength
mse                       283.692402      176.518211             125.547356
rmse                       16.843171       13.286016              11.204792
%                           6.833797        0.944843               3.422623

In [30]:
error=calc_error_margin(predx, test)
error

      abdominalextensiondepthsitting  acromialheight  acromionradialelength
mse                       937.055874     7079.766502             391.245600
rmse                       30.611368       84.141348              19.779929
%                          12.419983        5.983762               6.041990

In [28]:
error=calc_error_margin(p3, test)
error

      abdominalextensiondepthsitting  acromialheight  acromionradialelength
mse                       266.796921      154.474505             135.351917
rmse                       16.333919       12.428777              11.634084
%                           6.627178        0.883880               3.553755

In [26]:
error=calc_error_margin(predx, test)
error

,abdominalextensiondepthsitting,acromialheight,acromionradialelength,anklecircumference,axillaheight,balloffootcircumference
mse,230.330627,214.331088,196.564483,129.729450,149.867546,178.724867
rmse,15.176647,14.640051,14.020146,11.389884,12.242040,13.368802
%,6.157637,1.041136,4.282603,5.064615,0.941979,5.474695

In [23]:
error=calc_error_margin(p2, test)
error

      abdominalextensiondepthsitting  acromialheight  acromionradialelength
mse                     21939.775441    80492.483051            3677.122437
rmse                      148.120814      283.711972              60.639281
%                          60.097213       20.176346              18.522914

In [21]:
error=calc_error_margin(p, test)
error

      abdominalextensiondepthsitting  acromialheight  acromionradialelength
mse                       937.055874     7079.766502             391.245600
rmse                       30.611368       84.141348              19.779929
%                          12.419983        5.983762               6.041990

In [10]:
error=calc_error_margin(predb, test)
error

      neckcircumference
mse          453.017302
rmse          21.284203
%              5.669118

In [ ]:
predbmb=pd.read_csv('../output/anthro_results/predict_test_bambi10.csv')
test=pd.read_csv('../data/processed/ANSURIItest.csv')
predbmb=predbmb[:5]

In [50]:
calc_error_margin(predbmb, test)

,abdominalextensiondepthsitting,acromialheight,acromionradialelength,anklecircumference,axillaheight
mse,207.900302,370.333332,292.171335,160.193521,182.843014
rmse,14.418748,19.244047,17.093020,12.656758,13.521946
%,5.850134,1.368552,5.221245,5.627942,1.040463

In [55]:
predc=pd.read_csv('../output/anthro_results/predict_test_bambi_c10.csv')
test=pd.read_csv('../data/processed/ANSURIItest.csv')
predc=predc[:5]
calc_error_margin(predc, test)

,abdominalextensiondepthsitting,acromialheight,acromionradialelength,anklecircumference,axillaheight
mse,207.804037,378.518236,290.916524,160.364936,187.416905
rmse,14.415410,19.455545,17.056275,12.663528,13.690029
%,5.848779,1.383593,5.210021,5.630953,1.053396